### ISSUE TITLE
fabrication::support doesn't work with AS inflections

### ISSUE THREAD

**Issue by jennyfer** [paulelliott/fabrication#234]
The singleton method "variable_name_to_class_name" doesn't take specific configuration of active support inflector, this can result in Fabrication::UnfabricatableError error.

We work out this problem by rewriting this method like:
```ruby
class Fabrication::Support
  class << self
    def variable_name_to_class_name(name)
      name.to_s.classify
    end
  end
end
```
using the active support classify method (http://apidock.com/rails/ActiveSupport/Inflector/classify)

You may want to do it in your master branch.

**Comment by paulelliott** [comment]
Fabrication has no dependencies so we can't rely on the presence of activesupport. We are aware of it if it is loaded though, so using this when available is definitely worth doing. Thanks for bringing it to my attention!

**Comment by paulelliott** [comment]
Version 2.12.0 includes this change.

**Comment by paulelliott** [comment]
I apologize, but I had to revert this commit and go back to the old way of resolving classes. As soon as I pushed this out, a number of users began having issues in their apps largely due to classify's use of singularize.

If you are having trouble resolving certain classes in your app, try setting the class_name explicitly in your fabricator definition.

**Comment by jennyfer** [comment]
ok thanks
