### ISSUE TITLE
What is the shebang for?

### ISSUE THREAD

**Issue by osmancrush** [paulelliott/fabrication#252]
I've inherited some specs that contain the following

```Fabricator(:tenant_user) do
  user!
  tenant!
end```

For the life of me I can't find any documentation to detail what the shebang is actually for... any ideas - or ideally a link to documentation?

**Comment by paulelliott** [comment]
That is an old syntax that was deprecated with version 2.0.0. If you are on a newer version than that you can safely remove them.

If you're on an older version, those tell Fabrication to generate the model immediately instead of on 1st access. Without them it will wait until you actually call the field accessor to generate the associated model.

**Comment by osmancrush** [comment]
Thanks for responding so quickly!
