### ISSUE TITLE
rails4 issues in relation attributes

### ISSUE THREAD

**Issue by 3zone** [paulelliott/fabrication#258]
I have an A.R. model in Rails3, working without problem with Fabrication gem:

```ruby
class Location < ActiveRecord::Base
  belongs_to :typo, :foreign_key => "typo_id", :class_name => "TypoSite"
  has_many :typo_visibilities, :class_name => "LocationVisibilityTypo"
  has_many :typos, :through => :typo_visibilities

  # other stuff
end
```

and relative fabricator:

```ruby
Fabricator(:location) do
  typo(fabricator: :typo_site)
  typo_ids { |attrs| [ attrs[:typo][:id] ] }
  # other stuff
end
```

but after migration to rails4 the fabricator don't set the "typo_id" and "typo_ids" fields.
even if I specify it like this:

```ruby
t = Fabricate :typo_site
Fabricate :location, typo_id: t.id, typo_ids: [t.id]
```

the returned record have "typo_id" and "typo_ids" empty.

**Comment by paulelliott** [comment]
You're seeing a difference here because AR4 internals are a little bit different than AR3. I generally recommend that you do not set ids directly when using AR because it can produce some weird behavior such as this. If you must set ids, you must *always* set ids and not mix them with model setters.

The crux of the issue is that when you fabricate the location, you are actually creating *two* typo_sites. When you pass `typo_id` into Fabricate, both the `typo_id` and `typo` fields are being passed to AR and AR is determining which one takes precedence. Try this instead and I think you'll have a better result:

```
Fabricator(:location) do
  typo(fabricator: :typo_site)
  typos { |attrs| [attrs[:typo]].compact }
end

t = Fabricate :typo_site
Fabricate :location, typo: t
```
