### ISSUE TITLE
Default transient attribute values not available when a fabricator overrides an attribute definition

### ISSUE THREAD

**Issue by brentsnook** [paulelliott/fabrication#259]
We have noticed weird behaviour in fabricators that extend another and override an attribute definition; the attribute definition for the extending fabricator is used as expected but the default transient attributes are not available to it.

If the extending fabricator doesn't override an attribute from the base fabricator then everything works as expected.

If the extending fabricator is given a value for the transient attribute, everything is also fine.

This spec demonstrates the problem:

```ruby
require 'rspec'
require 'fabrication'

class Animal
  attr_accessor :description
end

Fabricator(:animal, class_name: Animal) do
  description do
    'some sort of animal'
  end
end

Fabricator(:dog, from: :animal) do
  transient :name
  name { 'Fido' }

  description do |attrs|
    "a dog named #{attrs[:name]}"
  end
end

RSpec.describe 'transient attributes' do
  let(:dog) { Fabricate.build(:dog) }

  context 'used in an overridden attribute definition' do
    it 'uses the default value when none is specified' do
      expect(dog.description).to eq('a dog named Fido')
    end
  end
end
```

Using the latest (2.14.1) on MRI 2.2.1

**Comment by paulelliott** [comment]
This issue actually doesn't have anything to do with transients. It is because in your parent fabricator you defined `description`, which locks in its evaluation order. When you override it in `dog`, it is still being processed first because it was the first attribute named in the whole chain of fabricators.

You can fix the issue by adding the transient to the base fabricator with a nil value.

* The reason passing it in fixes it is because values passed as attributes to `Fabricate` are always made available first.

**Comment by nruth** [comment]
This is weird behaviour. Doesn't inheritance usually evaluate in the opposite direction?
