### ISSUE TITLE
How to handle before_create build_profile with fabricators?

### ISSUE THREAD

**Issue by AlexVPopov** [paulelliott/fabrication#265]
A common situation:
```ruby
class User < ActiveRecord::Base
  has_one :profile
  before_create { build_profile }
end

class Profile < ActiveRecord::Base
  belongs_to :user
end
```
Fabricators:
```ruby
Fabricator(:user) { }

Fabricator(:profile) { user }
```
When one fabricates a user (`Fabricate :user`) everything is ok. However, when one fabricates a profile (`Fabricate :profile`), there are two profiles created with the same `user_id` - one created by the fabricator and one created by the `before_create` callback. Is this the expected behavior? Isn't `Fabrication` supposed to guess that the first profile is the one, that is supposed to be called by callback?

**Comment by paulelliott** [comment]
I think fabrication is persisting the user defined in your profile fabricator before persisting the profile itself. That means the callback in your model is executed, then fabrication makes the profile you asked for, then assigns the user to it creating the two profiles.

First, check to make sure you are only creating the profile if one doesn't exist already. If you aren't, do that and your problem may go away.

If that doesn't fix it, leave that change and adjust your fabricator to `build` the user instead of persisting it.

```
Fabricator(:profile) do
  user { Fabricate.build(:user) }
end
```

**Comment by AlexVPopov** [comment]
Thank you, that fixed it. I added:
```ruby
before_create { build_profile unless profile }
```
but that didn't help, so I added:
```ruby
user { Fabricate.build(:user) }
```
which solved it. Thank you :+1: :smile:
