### ISSUE TITLE
Program cannot find fabricators

### ISSUE THREAD

**Issue by volkanunsal** [paulelliott/fabrication#52]
I have 3 fabricators called flow, node and user in the spec/fabricators folder. However when I call Fabricate on any one of them, I get 2 kinds of errors. 

1) Fabrication::UnknownFabricatorError: No Fabricator defined for 'user'

and the slightly more puzzling

2) Fabrication::UnfabricatableError: No class found for 'client'

I'm not sure why it's trying to find a class called client. I do have a fabricator and a model named client, but this is happening when I do 

         ruby-1.9.2-p180 :001 > Fabricate(:node)

Node model does not have any relationship to client. 

(I'm using version 1.0.1)

**Comment by habitullence** [comment]
Looks like I'm having the same problem.

**Comment by paulelliott** [comment]
@habitullence could you provide more information about your error? Stack trace, etc?

**Comment by habitullence** [comment]
@paulelliott sorry, I wasn't very helpful. Here you go https://gist.github.com/habitullence/a1f785f855a1495dfce4

**Comment by supremebeing7** [comment]
Hi there, I got this `Fabrication::UnknownFabricatorError: No Fabricator defined for 'user'` error as well, even though I've been using my user fabricator without issue and I hadn't changed it at all. I finally realized that it was giving me this error when the REAL error was because I had deleted an Authentication class but had not removed the associated Authentication fabricator.

I hope this helps someone else who stumbles on this from Google. @paulelliott Can I suggest a more helpful error message for this scenario? I can try to throw together a PR for that later this week.

**Comment by paulelliott** [comment]
@supremebeing7 a PR would be wonderful :)

**Comment by supremebeing7** [comment]
This was not nearly as simple as I thought it would be to implement, especially considering that I've had trouble reproducing the error consistently. I've been swamped lately and haven't had a chance to take another run at this, so if anyone else wants to jump in, I say go for it.
